# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backend_and_gpu.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62\x61\x63kend_and_gpu.proto\x12\x1d\x63om.sophgo.lmcs.backend.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x01\n\x15NotifyInferenceStatus\x12\x11\n\ttask_uuid\x18\x01 \x01(\t\x12\r\n\x05\x65vent\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x14\n\x0crelease_time\x18\x04 \x01(\t\"Z\n\x0cServerStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08LAUNCHED\x10\x01\x12\x15\n\x11RELEASE_SCHEDULED\x10\x02\x12\r\n\tEXCEPTION\x10\x03\x12\t\n\x05READY\x10\x04\"\xd3\x01\n\x14NotifyFinetuneStatus\x12\x11\n\ttask_uuid\x18\x01 \x01(\t\x12\r\n\x05\x65vent\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x14\n\x0crelease_time\x18\x04 \x01(\t\x12\x11\n\tlora_path\x18\x05 \x01(\t\"]\n\x0cServerStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08LAUNCHED\x10\x01\x12\x15\n\x11RELEASE_SCHEDULED\x10\x02\x12\r\n\tEXCEPTION\x10\x03\x12\x0c\n\x08\x46INISHED\x10\x04\x42+\n\'com.sophgo.lmcs.backend.proto.generatedP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backend_and_gpu_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\'com.sophgo.lmcs.backend.proto.generatedP\001'
  _NOTIFYINFERENCESTATUS._serialized_start=90
  _NOTIFYINFERENCESTATUS._serialized_end=280
  _NOTIFYINFERENCESTATUS_SERVERSTATUS._serialized_start=190
  _NOTIFYINFERENCESTATUS_SERVERSTATUS._serialized_end=280
  _NOTIFYFINETUNESTATUS._serialized_start=283
  _NOTIFYFINETUNESTATUS._serialized_end=494
  _NOTIFYFINETUNESTATUS_SERVERSTATUS._serialized_start=401
  _NOTIFYFINETUNESTATUS_SERVERSTATUS._serialized_end=494
# @@protoc_insertion_point(module_scope)
